---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vue43
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: element43
        e43-service: vue43
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: vue43
        image: evetools/vue43:latest
        imagePullPolicy: Always
        env:
        - name: HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  name: vue43
spec:
  selector:
    app: element43
    e43-service: vue43
  ports:
    - name: http
      port: 3000
      targetPort: 3000
